Add boss spSpec path to sdss5
sdss/tree pull request #31
Opened 2021-07-27 07:52 UTC by andycasey

As far as I can see, there aren't any path definitions for BOSS co-added spectra in the SDSS-V tree definitions. I think this is the correct definition, but I would like @hjibarram to confirm.

(I am opening this pull request because I would like Astra to run nicely on BOSS spectra without me having to write edge cases in for dealing with BOSS spectra).

2021-07-27 14:53 UTC, hjibarram commented
Hi Andy, the spSpec files weren't considered a final dataproduct, the
spSpec files are intermediate files between the coadd phase and the 1d
phase of the pipeline, the final 1d spectra are the spec files (
https://data.sdss5.org/sas/sdsswork/bhm/boss/spectro/redux/master/spectra/full/
or $BOSS_SPECTRA_REDUX/$RUN2D/spectra/full). On the other hand, if the
spSpec files are needed for Astra, there isn't any inconvenient for the
part of the boss pipeline to include the path of the spSpec files to the
sdss/tree

Cheers
Hector Ibarra

On Tue, Jul 27, 2021 at 2:52 AM Andy Casey ***@***.***> wrote:

> As far as I can see, there aren't any path definitions for BOSS co-added
> spectra in the SDSS-V tree definitions. I think this is the correct
> definition, but I would like @hjibarram <https://github.com/hjibarram> to
> confirm.
>
> (I am opening this pull request because I would like Astra to run nicely
> on BOSS spectra without me having to write edge cases in for dealing with
> BOSS spectra).
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/sdss/tree/pull/31
> Commit Summary
>
>    - Add boss spSpec path to sdss5
>
> File Changes
>
>    - *M* data/sdss5.cfg
>    <https://github.com/sdss/tree/pull/31/files#diff-9d530ac4e826912b7a241015684005811596a5840839c275f58c43a2dbd4188e>
>    (3)
>
> Patch Links:
>
>    - https://github.com/sdss/tree/pull/31.patch
>    - https://github.com/sdss/tree/pull/31.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdss/tree/pull/31>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFTRCK36YBNI6RQWWDWDXP3TZZQUBANCNFSM5BBVLWHA>
> .
>

2021-07-28 13:48 UTC, havok2063 requested changes
I think it's ok to include path definitions for raw and intermediate products.  Ultimately, we want to define these paths for every single file produced in SDSS, from raw to final to VAC product.

2021-07-28 13:48 UTC, havok2063 commented on data/sdss5.cfg
> +spSpec = $BOSS_SPECTRO_REDUX/{run2d}/{plate}p/coadd/{mjd}/spSpec-{plate}-{mjd}-{max(fiberid, catalogid):0>11}.fits
The paths for `tree` and `sdss_access` don't support complex operations or functions for the variable substitution syntax.  We're not currently using f-strings, just a simple string substitution via `.format`.  I don't think `{max(fiberid, catalogid)}` will work in that mode.  Can you simplify those keyword variables?  I would recommend making these path definitions as simple as possible.

Alternatively if you really want to take the max of either variable, you could define a special function using the `@[name()]|` syntax, e.g. the `apField` entry.  Then define that function in `sdss_access.path.Path`.

2021-07-30 07:48 UTC, andycasey commented
@hjibarram: I will try to use the 'spec' files for the analysis then. I wasn't sure if 'spSpec' was the final data product or not. 

Is the 'spec' file format in the tree already? I can't see it in the 'sdss5' release.


If 'spSpec' is to have a data model specification, then I'll need @hjibarram to confirm that the format I proposed here is the one that was decided on (e.g., the max of fiberid and catalogid).

2021-07-30 14:48 UTC, havok2063 commented
The `spec` and `spec-lite` paths are not yet in the `sdss5` config file.  They are in `sdsswork` via the `basework` config file.  I would go ahead and define new variables for `spec`, etc in the `sdss5` config.  At some point we'll migrate `sdss5` over to be the new `sdsswork`, and migrate any old paths over, but for now, we should just add what we need in `sdss5`.

If `spSpec` is an intermediate product that will eventually be released, then yeah it will need a datamodel specification.  We are also trying to move to a system where every file regardless if it's released or not will have a datamodel specification.  So I would lean towards adding an entry.

2021-07-30 16:53 UTC, hjibarram commented
"If spSpec is an intermediate product that will eventually be released,
then yeah it will need a datamodel specification. "
Yes, all the data products for the boss-pipeline (final and intermediate)
are described here:

https://wiki.sdss.org/display/DATAMODEL/BOSS_SPECTRO_REDUX

But I discovered that there is a problem with the automatic wiki-page
generation. The yaml files that describe the data models exist in
$DATAMODEL_DIR/data/yaml/BOSS_SPECTRO_REDUX.

Hector Ibarra

On Fri, Jul 30, 2021 at 9:48 AM Brian Cherinka ***@***.***>
wrote:

> The spec and spec-lite paths are not yet in the sdss5 config file. They
> are in sdsswork via the basework config file. I would go ahead and define
> new variables for spec, etc in the sdss5 config. At some point we'll
> migrate sdss5 over to be the new sdsswork, and migrate any old paths
> over, but for now, we should just add what we need in sdss5.
>
> If spSpec is an intermediate product that will eventually be released,
> then yeah it will need a datamodel specification. We are also trying to
> move to a system where every file regardless if it's released or not will
> have a datamodel specification. So I would lean towards adding an entry.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdss/tree/pull/31#issuecomment-889943329>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFTRCK652JM3SXL3TJWLRB3T2K3TRANCNFSM5BBVLWHA>
> .
>

2021-08-03 09:48 UTC, andycasey commented
I cannot see the definitions you describe, either on that Wiki page (see attached), or in the tree product file itself.

![image](https://user-images.githubusercontent.com/504436/127995472-7fa0d51d-44a4-453e-abb2-a0ead254cb2b.png)

Could you point me to another location where the file path is defined?

2021-08-03 16:20 UTC, hjibarram commented
Hi, to access to the yaml files, it is necessary to load the module
datamodel (module load datamodel), then go to the main directory for the
boos pipeline datamodel definition:

cd $DATAMODEL_DIR/data/yaml/BOSS_SPECTRO_REDUX, in that directory are
located the dataproduct definition (according with their tree definitions),
for example:

$DATAMODEL_DIR/data/yaml/BOSS_SPECTRO_REDUX/RUN2D/spectra/full/PLATEp/MJD/spec.yaml

Cheers
Hector Ibarra



On Tue, Aug 3, 2021 at 4:48 AM Andy Casey ***@***.***> wrote:

> I cannot see the definitions you describe, either on that Wiki page (see
> attached), or in the tree product file itself.
>
> [image: image]
> <https://user-images.githubusercontent.com/504436/127995472-7fa0d51d-44a4-453e-abb2-a0ead254cb2b.png>
>
> Could you point me to another location where the file path is defined?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdss/tree/pull/31#issuecomment-891702813>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFTRCK3ODIOLQP2IWXQGICLT263OJANCNFSM5BBVLWHA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-04 02:09 UTC, havok2063 commented
The wiki page has been deleted because we are deprecating that space for the datamodel in favor of a standalone web interface for the datamodel.  That's why the pages no longer exist.  @hjibarram Have you made sure to update your checkout of the datamodel repo lately?   We've changed things a bit, due to the new versioning, and all the old datamodel files have been removed.  You will need to recreate the files you previously made so that they're in the new format.

2021-12-05 21:40 UTC, havok2063 commented
Closing this PR as this path has already been added.

2021-12-05 21:40 UTC, closed without merging