Add ipl3 astra paths
sdss/tree pull request #69
Opened 2023-10-08 21:55 UTC by andycasey

2023-10-10 16:37 UTC, havok2063 commented
In addition to updated paths in `sdsswork.cfg`, there should be a new `ipl3.cfg` with all the paths and envvars defined there.  If using IPL-2 as a base config, then only new or updated paths and envars needs to be included.

2023-10-10 16:43 UTC, havok2063 commented
See https://github.com/sdss/tree/issues/65

2023-10-10 17:10 UTC, joelbrownstein commented
We would need the ipl3.cfg after that top level folder has been created on the SAS.  We are currently staging ipl3 files in sdsswork, and since there are therefore no current paths starting with ipl3, then this action should be deferred until the sdsswork -> ipl3 copy is scheduled and completed.

2023-10-12 00:31 UTC, andycasey commented
OK. When the ipl3.cfg file is ready just @/ping me through some electronic medium and I will add these paths to the ipl3.cfg file. After discussion with @ajwheeler I have corrected some of these paths (I am an idiot who often makes mistakes). I think the paths are all correct now.

2023-10-17 00:10 UTC, havok2063 submitted a review, later dismissed

2023-10-17 15:38 UTC, ajwheeler commented on data/ipl3.cfg
> +astraAllStarSnowWhite  = $MWM_ASTRA/{v_astra}/{run2d}-{apred}/summary/astraAllStar-SnowWhite-{v_astra}-{run2d}-{apred}.fits
I think these are redundant?

2023-10-17 15:39 UTC, ajwheeler commented
Otherwise lgtm

2023-10-17 15:43 UTC, joelbrownstein commented
Hi @andycasey @ajwheeler @havok2063, I added a top-level ipl3 folder at /uufs/chpc.utah.edu/common/home/sdss/ipl-3, or on the SAS athttps://data.sdss5.org/sas/ipl-3; and I added the ipl3.cfg file and copied over boss_drp, apogee_drp, and astra paths from sdsswork.  Would you please check that the paths are OK in this branch so we can merge to main and install at Utah?

2023-10-17 15:56 UTC, havok2063 requested changes
The build/test action is failing.  As @ajwheeler noticed, there are redundant, duplicate, paths in the `ipl3.cfg`.  I think these are the cause of the failing action.   

Because the scope of this PR has now expanded, additional updates need to be added to the documentation and tests before we can merge this PR and tag a new release of tree.  Can you update the relevant rst files: `docs/sphinx/config.rst` and `tree_envs.rst`?    

Can you also add a small test in `test_tree.py` that loads the IPL-3 config and checks that a correct IPL-3 specific environment and path template are there?

2023-10-17 16:11 UTC, joelbrownstein commented
I added the test @havok2063 requested, but @andycasey or @ajwheeler would you please remove the duplicates from sdssword and ipl3 -- I don't know which to keep since the duplicates don't match!

2023-10-17 22:05 UTC, havok2063 commented
Currently I cannot read the ipl3 config in tree with the following error:  This is a straight error from `ConfigParser` reading in an ini file.  The ini file can't have duplicate named keys in any section. 
```
DuplicateOptionError: While reading from '/Users/Brian/Work/github_projects/sdss/tree/data/ipl3.cfg' [line 159]: option 'allCal' in section 'PATHS' already exists
```
I think large chunks of paths were just copied over for boss, apogee, and astra.

2023-10-17 22:38 UTC, joelbrownstein commented
I made an attempt to remove the duplicates.

2023-10-18 17:27 UTC, havok2063 commented
@ajwheeler Can you review the updated ipl3 config and just double check that everything looks ok after the cleanup of the duplicates?

2023-10-19 16:37 UTC, havok2063 approved these changes

2023-10-19 17:52 UTC, ajwheeler commented
Looks like the deduplication is correct.

2023-10-20 18:17 UTC, merged